import { expect, test } from "@playwright/test";
import AxeBuilder from "@axe-core/playwright";
import ExcelJS from "exceljs";

test("CSV upload, scoped workspace, replacement, rename and delete", async ({ page }, testInfo) => {
  await page.setViewportSize({ width: 1440, height: 900 });
  const errors: string[] = [];
  page.on("pageerror", (error) => errors.push(error.message));
  let enrichCalls = 0;
  page.on("request", (request) => { if (request.url().includes("/api/signals/refresh")) enrichCalls++; });
  await page.goto("/");
  await expect(page).toHaveURL(/\/lists$/);
  await page.getByRole("button", { name: "Upload new list" }).click();
  const dialog = page.getByRole("dialog");
  await dialog.getByLabel("CSV or XLSX file").setInputFiles({ name: "Healthcare targets.csv", mimeType: "text/csv", buffer: Buffer.from("account_name,website,vertical,tier,relationship_status,suggested_entry_offer\nHanger,\n") });
  await expect(dialog.getByRole("alert")).toContainText("Fix every error");
  await expect(dialog.getByRole("button", { name: "Import list", exact: true })).toBeDisabled();
  await dialog.getByLabel("CSV or XLSX file").setInputFiles({ name: "Healthcare targets.csv", mimeType: "text/csv", buffer: Buffer.from("account_name,website,vertical,tier,relationship_status,suggested_entry_offer\nHanger,hanger.com,Healthcare,1,Existing relationship,AI strategy and readiness\nNovant Health,novanthealth.org,Healthcare,1,Existing client,Contract intelligence\n") });
  await expect(dialog.getByText("2 new · 0 reused · 0 duplicates · 0 errors")).toBeVisible();
  await page.screenshot({ path: testInfo.outputPath("import-preview.png"), fullPage: true });
  const previewAxe = await new AxeBuilder({ page }).analyze();
  expect(previewAxe.violations.filter((item) => ["critical", "serious"].includes(item.impact || ""))).toEqual([]);
  await dialog.getByRole("button", { name: "Import list", exact: true }).click();
  await expect(dialog).not.toBeVisible();
  const card = page.getByRole("article", { name: "Healthcare targets", exact: true });
  await card.getByRole("link", { name: "Open list" }).click();
  await expect(page.locator(".account-row")).toHaveCount(2);
  await expect(page.getByRole("heading", { name: "Imported context — unverified" })).toBeVisible();
  await expect(page.getByRole("button", { name: "Enrich pending accounts" })).toBeDisabled();
  expect(enrichCalls).toBe(0);
  await expect(page.locator(".score-number").first()).toHaveText("0");
  await page.reload();
  await expect(page.locator(".account-row")).toHaveCount(2);
  await page.getByRole("link", { name: "Manage target lists" }).click();
  await card.getByRole("button", { name: "Replace from file" }).click();
  await dialog.getByLabel("CSV or XLSX file").setInputFiles({ name: "replacement.csv", mimeType: "text/csv", buffer: Buffer.from("account_name,website,tier\nHanger,hanger.com,2\n") });
  await expect(dialog.getByText("0 new · 1 reused · 0 duplicates · 0 errors")).toBeVisible();
  await dialog.getByRole("button", { name: "Replace list", exact: true }).click();
  await expect(dialog).not.toBeVisible();
  await card.getByRole("button", { name: "Rename", exact: true }).click();
  await dialog.getByLabel("List name").fill("Healthcare priorities");
  await dialog.getByRole("button", { name: "Save name" }).click();
  await expect(dialog).not.toBeVisible();
  const renamed = page.getByRole("article", { name: "Healthcare priorities" });
  await expect(renamed.locator(".list-counts dd").first()).toHaveText("1");
  await page.screenshot({ path: testInfo.outputPath("list-manager.png"), fullPage: true });
  await renamed.getByRole("button", { name: "Delete", exact: true }).click();
  await dialog.getByRole("button", { name: "Cancel" }).click();
  await expect(renamed).toBeVisible();
  await renamed.getByRole("button", { name: "Delete", exact: true }).click();
  await dialog.getByRole("button", { name: "Delete list", exact: true }).click();
  await expect(renamed).not.toBeVisible();
  expect(errors).toEqual([]);
});

test("XLSX import and list management fit a narrow viewport", async ({ page }, testInfo) => {
  await page.setViewportSize({ width: 390, height: 844 });
  const workbook = new ExcelJS.Workbook();
  const sheet = workbook.addWorksheet("Targets");
  sheet.addRow(["account_name", "website", "tier"]);
  sheet.addRow(["XLSX Example", "xlsx-example.com", 2]);
  await page.goto("/lists");
  await page.getByRole("button", { name: "Upload new list" }).click();
  const dialog = page.getByRole("dialog");
  await dialog.getByLabel("CSV or XLSX file").setInputFiles({ name: "XLSX targets.xlsx", mimeType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", buffer: Buffer.from(await workbook.xlsx.writeBuffer()) });
  await expect(dialog.getByText("1 new · 0 reused · 0 duplicates · 0 errors")).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(390);
  await page.screenshot({ path: testInfo.outputPath("narrow-import.png"), fullPage: true });
  await dialog.getByRole("button", { name: "Import list", exact: true }).click();
  await expect(dialog).not.toBeVisible();
  const result = await new AxeBuilder({ page }).analyze();
  expect(result.violations.filter((item) => ["critical", "serious"].includes(item.impact || ""))).toEqual([]);
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(390);
  await page.getByRole("article", { name: "XLSX targets" }).getByRole("button", { name: "Delete", exact: true }).click();
  await dialog.getByRole("button", { name: "Delete list", exact: true }).click();
});
